package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	B int `json:"b"`
	C int `json:"c"`
}

func main() {
	json_text := "{\"a\":1, \"b\":2, \"c\":3}"

	ac := AutoGenerated{}
	json.Unmarshal([]byte(json_text), &ac)
	fmt.Printf("%#v\n", ac)
}
